### ISSUE TITLE
when the object is too large in the picture,program will crash

### ISSUE THREAD

**Issue by obplay** [chandrikadeb7/Face-Mask-Detection#26]
try to add the borders of picture to can be a solution.

**Comment by aaramg** [comment]
@obplay have you solved the problem?? Could you provide the code?

**Comment by NomadicCode** [comment]
same issue here

**Comment by NomadicCode** [comment]
here's the output ```py
2020-08-25 18:16:48.487408: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-08-25 18:16:48.487451: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[INFO] loading face detector model...
[INFO] loading face mask detector model...
2020-08-25 18:16:50.071517: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-08-25 18:16:50.071549: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-08-25 18:16:50.071577: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (the-coders-hub-192): /proc/driver/nvidia/version does not exist
2020-08-25 18:16:50.093712: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2495195000 Hz
2020-08-25 18:16:50.094102: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x563076a54590 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-25 18:16:50.094133: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[INFO] starting video stream...
[ WARN:0] global /build/opencv/src/opencv-4.4.0/modules/videoio/src/cap_gstreamer.cpp (935) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
Traceback (most recent call last):
  File "detect_mask_video.py", line 114, in <module>
    (locs, preds) = detect_and_predict_mask(frame, faceNet, maskNet)
  File "detect_mask_video.py", line 55, in detect_and_predict_mask
    face = cv2.cvtColor(face, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.4.0) /build/opencv/src/opencv-4.4.0/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

FATAL: exception not rethrown
Aborted (core dumped)
```

**Comment by mvssanjay007** [comment]
import cv2 as cv
img=cv.imread('w.jpg',0)
w,h=img.shape
img=cv.resize(img,(h//10,w//10))
cv.imwrite('w1.jpg',img)

You can try this with varying filenames and ratios(Here I used 10, you can use your ratio)
