### ISSUE TITLE
Face Mask detection Error

### ISSUE THREAD

**Issue by Mony24** [chandrikadeb7/Face-Mask-Detection#44]
Getting following error
sudo python3 detect_mask_video.py 
2020-11-17 14:44:36.808007: E tensorflow/core/platform/hadoop/hadoop_file_system.cc:132] HadoopFileSystem load error: libhdfs.so: cannot open shared object file: No such file or directory
..............
Traceback (most recent call last):
  File "detect_mask_video.py", line 98, in <module>
    maskNet = load_model(args["model"])
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/saving/save.py", line 149, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/saved_model/loader_impl.py", line 83, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: mask_detector.model/{saved_model.pbtxt|saved_model.pb}

Also getting following error
(fmdt1-env) pi@raspberrypi:~/FMDet1 $ sudo pip3 install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement tensorflow>=1.15.2 (from -r requirements.txt (line 1)) (from versions: 0.11.0, 1.12.0, 1.13.1, 1.14.0)
ERROR: No matching distribution found for tensorflow>=1.15.2 (from -r requirements.txt (line 1))
(fmdt1-env) pi@raspberrypi:~/FMDet1 $ sudo pip3 show tensorflow

**Comment by vinamramunot-tech** [comment]
@Mony24 I have the same error

**Comment by vinamramunot-tech** [comment]
I actually found the solution for this. @chandrikadeb7 Please let me know if you would like a solution for this. I have written this for raspberry pi running raspbian OS 32-bit.

**Comment by vinamramunot-tech** [comment]
@Mony24 are you running this on raspberry pi?
